### ISSUE TITLE
How to help enhancing the translation of this app?

### ISSUE THREAD

**Issue by buzhangjiuzhou** [Goodwy/4Messages#5]
First of all, thanks to qksms and your efforts in developing and mantaining this excellent app!

During my usage, I found out that the Chinese version mixed Simplified Chinese (which is shown for many words) and Traditional Chinese (which is shown for some words). while there's some apparent differences, I am wishing to have an enhanced Simplified version(I am not so familiar with Traditional one) and willing to give out some hands.

However, I don't know how to build an android app, so I can't find the way to do this. Can you give me some instructions ?

**Comment by Goodwy** [comment]
Write me an email (goodwy.dev@gmail) which phrases are not correct and what they should be.
Instructions for correcting translations are here - https://github.com/Goodwy/Discussion
