### ISSUE TITLE
Google Analytics?

### ISSUE THREAD

**Issue by ferrum** [Goodwy/4Messages#6]
Aurora store detects it is using Google Analytics (QKSMS does not appear to have them), is that true?

**Comment by Goodwy** [comment]
This is the legacy of QKSMS. You most likely used QKSMS not from Google Play, but from F-Droid. Google Analytics is used in the Google Play version.

**Comment by ferrum** [comment]
@Goodwy thank you for the explaination, I apologize for my assertation without further analyzing it. Keep up the good work!
